name: task_manager_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Packages
  sqflite: ^2.0.0+4
  path_provider: ^2.0.9
  intl: ^0.17.0
  flutter_local_notifications: ^17.2.4
  permission_handler: ^10.2.0
  audioplayers: ^6.1.0
  timezone: ^0.9.4
  file_picker: ^8.1.3
  share_plus: ^10.1.2
  csv: ^5.0.0
  pdf: ^3.11.1
  printing: ^5.0.0
  fl_chart: ^0.40.0
  shared_preferences: ^2.3.3
  carousel_slider: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Add your assets here
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/8.png
    - assets/9.png
    - assets/10.png
    - assets/11.png
    - assets/12.png
    - assets/13.png
    - assets/14.png